class IODataBase:
    def read(self, filepath): ...
    def save(self, path): ...
    def __len__(self)->int: ...
    def __getitem__(self, idx: int):...
    def height(self):...
    def width(self):...

